output "db_endpoint" {
  description = "RDS endpoint host (no port)"
  value       = aws_db_instance.pgpilot.address
}

output "db_port" {
  value = aws_db_instance.pgpilot.port
}

output "db_password" {
  description = "Master password generated by Terraform"
  value       = random_password.db.result
  sensitive   = true
}
