apiVersion: 1

datasources:
  - name: PGPilot
    uid: pgpilot-postgres
    type: postgres
    url: ${DB_HOST}:5432
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: ${GF_DB_SSLMODE}
      postgresVersion: 1600
    isDefault: true
    editable: true
